apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: dr-vault
spec:
  request: $(cat vault-dr.csr | base64 | tr -d "\n")
  signerName: kubernetes.io/kube-apiserver-client-kubelet
  usages:
  - digital signature
  - key encipherment
  - server auth