apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: primary-vault
  namespace: vault-ns
spec:
  request: $(cat vault-primary.csr | base64 | tr -d "\n")
  signerName: kubernetes.io/kube-apiserver-client-kubelet
  usages:
  - digital signature
  - key encipherment
  - server auth
